AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.

Resources:
  LF2:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: ./lf2/
      Description: ''
      MemorySize: 528
      Timeout: 30
      Role: >-
        arn:aws:iam::189187153403:role/serverlessrepo-s3-image-indexe-IndexerFunctionRole-1B7JN8PGHDO3H
  IndexerFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: 'Run Rekognition detect labels from S3 events and store results in ElasticSearch.'
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./lfes/
      Timeout: 30
      Role: >-
        arn:aws:iam::189187153403:role/serverlessrepo-s3-image-indexe-IndexerFunctionRole-1B7JN8PGHDO3H
      Environment:
        Variables:
          ELASTICSEARCH_URL: search-assignment-3-embfkaeetlkbbmtru7xvvuca5i.us-west-2.es.amazonaws.com
      Events:
        S3JpgEvent:
          Type: S3
          Properties:
            Bucket: !Ref ImageBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  -
                    Name: suffix
                    Value: jpg
        S3PngEvent:
          Type: S3
          Properties:
            Bucket: !Ref ImageBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  -
                    Name: suffix
                    Value: png
  ImageBucket:
    Type: 'AWS::S3::Bucket'